language: cpp
sudo: true

branches:
  only:
    - master

matrix:
  include:

  - os: linux
    dist: trusty
    compiler: clang
    env:
      - C_COMPILER_PACKAGE=clang-3.6
      - C_COMPILER_BIN=clang-3.6
      - CPP_COMPILER_PACKAGE=clang-3.6
      - CPP_COMPILER_BIN=clang++-3.6
      - COV_TOOL=llvm-cov-3.6
      - COV_TOOL_ARGS=gcov
    addons:
      apt:
        packages:
          - 'cmake3'
          - 'clang-3.6'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'
          - 'llvm-3.6-tools'

  - os: linux
    dist: trusty
    compiler: clang
    env:
      - C_COMPILER_PACKAGE=clang-3.8
      - C_COMPILER_BIN=clang-3.8
      - CPP_COMPILER_PACKAGE=clang-3.8
      - CPP_COMPILER_BIN=clang++-3.8
      - COV_TOOL=llvm-cov-3.8
      - COV_TOOL_ARGS=gcov
    addons:
      apt:
        packages:
          - 'cmake3'
          - 'clang-3.8'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'
          - 'llvm-3.8'

  - os: linux
    dist: trusty
    compiler: clang
    env:
      - C_COMPILER_PACKAGE=clang-3.9
      - C_COMPILER_BIN=clang-3.9
      - CPP_COMPILER_PACKAGE=clang-3.9
      - CPP_COMPILER_BIN=clang++-3.9
      - COV_TOOL=llvm-cov-3.9
      - COV_TOOL_ARGS=gcov
    addons:
      apt:
        packages:
          - 'cmake3'
          - 'clang-3.9'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'
          - 'llvm-3.9-tools'

  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - C_COMPILER_PACKAGE=gcc-4.4
      - C_COMPILER_BIN=gcc-4.4
      - CPP_COMPILER_PACKAGE=g++-4.4
      - CPP_COMPILER_BIN=g++-4.4
      - COV_TOOL=gcov-4.4
      - COV_TOOL_ARGS=
    addons:
      apt:
        packages:
          - 'cmake3'
          - 'gcc-4.4'
          - 'g++-4.4'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'

  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - C_COMPILER_PACKAGE=gcc-4.6
      - C_COMPILER_BIN=gcc-4.6
      - CPP_COMPILER_PACKAGE=g++-4.6
      - CPP_COMPILER_BIN=g++-4.6
      - COV_TOOL=gcov-4.6
      - COV_TOOL_ARGS=
    addons:
      apt:
        packages:
          - 'cmake3'
          - 'gcc-4.6'
          - 'g++-4.6'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'

  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - C_COMPILER_PACKAGE=gcc-4.7
      - C_COMPILER_BIN=gcc-4.7
      - CPP_COMPILER_PACKAGE=g++-4.7
      - CPP_COMPILER_BIN=g++-4.7
      - COV_TOOL=gcov-4.7
      - COV_TOOL_ARGS=
    addons:
      apt:
        packages:
          - 'cmake3'
          - 'gcc-4.7'
          - 'g++-4.7'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'

  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - C_COMPILER_PACKAGE=gcc-4.8
      - C_COMPILER_BIN=gcc-4.8
      - CPP_COMPILER_PACKAGE=g++-4.8
      - CPP_COMPILER_BIN=g++-4.8
      - COV_TOOL=gcov-4.8
      - COV_TOOL_ARGS=
    addons:
      apt:
        packages:
          - 'cmake3'
          - 'gcc-4.8'
          - 'g++-4.8'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'

  - os: linux
    dist: xenial
    compiler: clang
    env:
      - C_COMPILER_PACKAGE=clang-3.5
      - C_COMPILER_BIN=clang-3.5
      - CPP_COMPILER_PACKAGE=clang-3.5
      - CPP_COMPILER_BIN=clang++-3.5
      - COV_TOOL=llvm-cov-3.5
      - COV_TOOL_ARGS=gcov
    addons:
      apt:
        packages:
          - 'cmake'
          - 'clang-3.5'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'
          - 'llvm-3.5-tools'

  - os: linux
    dist: xenial
    compiler: clang
    env:
      - C_COMPILER_PACKAGE=clang-3.6
      - C_COMPILER_BIN=clang-3.6
      - CPP_COMPILER_PACKAGE=clang-3.6
      - CPP_COMPILER_BIN=clang++-3.6
      - COV_TOOL=llvm-cov-3.6
      - COV_TOOL_ARGS=gcov
    addons:
      apt:
        packages:
          - 'cmake'
          - 'clang-3.6'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'
          - 'llvm-3.6-tools'

  - os: linux
    dist: xenial
    compiler: clang
    env:
      - C_COMPILER_PACKAGE=clang-3.7
      - C_COMPILER_BIN=clang-3.7
      - CPP_COMPILER_PACKAGE=clang-3.7
      - CPP_COMPILER_BIN=clang++-3.7
      - COV_TOOL=llvm-cov-3.7
      - COV_TOOL_ARGS=gcov
    addons:
      apt:
        packages:
          - 'cmake'
          - 'clang-3.7'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'
          - 'llvm-3.7-tools'

  - os: linux
    dist: xenial
    compiler: clang
    env:
      - C_COMPILER_PACKAGE=clang-3.8
      - C_COMPILER_BIN=clang-3.8
      - CPP_COMPILER_PACKAGE=clang-3.8
      - CPP_COMPILER_BIN=clang++-3.8
      - COV_TOOL=llvm-cov-3.8
      - COV_TOOL_ARGS=gcov
    addons:
      apt:
        packages:
          - 'cmake'
          - 'clang-3.8'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'
          - 'llvm-3.8-tools'

  - os: linux
    dist: xenial
    compiler: clang
    env:
      - C_COMPILER_PACKAGE=clang-4.0
      - C_COMPILER_BIN=clang-4.0
      - CPP_COMPILER_PACKAGE=clang-4.0
      - CPP_COMPILER_BIN=clang++-4.0
      - COV_TOOL=llvm-cov-4.0
      - COV_TOOL_ARGS=gcov
    addons:
      apt:
        packages:
          - 'cmake'
          - 'clang-4.0'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'
          - 'llvm-4.0-tools'

  - os: linux
    dist: xenial
    compiler: clang
    env:
      - C_COMPILER_PACKAGE=clang-5.0
      - C_COMPILER_BIN=clang-5.0
      - CPP_COMPILER_PACKAGE=clang-5.0
      - CPP_COMPILER_BIN=clang++-5.0
      - COV_TOOL=llvm-cov-5.0
      - COV_TOOL_ARGS=gcov
    addons:
      apt:
        packages:
          - 'cmake'
          - 'clang-5.0'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'
          - 'llvm-5.0-tools'

  - os: linux
    dist: xenial
    compiler: clang
    env:
      - C_COMPILER_PACKAGE=clang-6.0
      - C_COMPILER_BIN=clang-6.0
      - CPP_COMPILER_PACKAGE=clang-6.0
      - CPP_COMPILER_BIN=clang++-6.0
      - COV_TOOL=llvm-cov-6.0
      - COV_TOOL_ARGS=gcov
    addons:
      apt:
        packages:
          - 'cmake'
          - 'clang-6.0'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'
          - 'llvm-6.0-tools'

  - os: linux
    dist: xenial
    compiler: gcc
    env:
      - C_COMPILER_PACKAGE=gcc-4.7
      - C_COMPILER_BIN=gcc-4.7
      - CPP_COMPILER_PACKAGE=g++-4.7
      - CPP_COMPILER_BIN=g++-4.7
      - COV_TOOL=gcov-4.7
      - COV_TOOL_ARGS=
    addons:
      apt:
        packages:
          - 'cmake'
          - 'gcc-4.7'
          - 'g++-4.7'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'

  - os: linux
    dist: xenial
    compiler: gcc
    env:
      - C_COMPILER_PACKAGE=gcc-4.8
      - C_COMPILER_BIN=gcc-4.8
      - CPP_COMPILER_PACKAGE=g++-4.8
      - CPP_COMPILER_BIN=g++-4.8
      - COV_TOOL=gcov-4.8
      - COV_TOOL_ARGS=
    addons:
      apt:
        packages:
          - 'cmake'
          - 'gcc-4.8'
          - 'g++-4.8'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'

  - os: linux
    dist: xenial
    compiler: gcc
    env:
      - C_COMPILER_PACKAGE=gcc-4.9
      - C_COMPILER_BIN=gcc-4.9
      - CPP_COMPILER_PACKAGE=g++-4.9
      - CPP_COMPILER_BIN=g++-4.9
      - COV_TOOL=gcov-4.9
      - COV_TOOL_ARGS=
    addons:
      apt:
        packages:
          - 'cmake'
          - 'gcc-4.9'
          - 'g++-4.9'
          - 'libssl-dev'
          - 'libcurl4-openssl-dev'
          - 'gdb'
          - 'valgrind'
          - 'lcov'

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

before_script:
  - export CXX=${CPP_COMPILER_BIN}
  - export C=${C_COMPILER_BIN}
  - cd ${TRAVIS_BUILD_DIR}

  # Enable core dumps
  - ulimit -c
  - ulimit -a -S
  - ulimit -a -H

  # Print debug system information
  - cat /proc/sys/kernel/core_pattern
  - cat /etc/default/apport
  - service --status-all || true
  - initctl list || true

  # Debug build
  - cmake -H.
    -BBuild-Debug
    -DCMAKE_BUILD_TYPE=Debug
    -DPISTACHE_BUILD_EXAMPLES=true
    -DPISTACHE_BUILD_TESTS=true
    -DPISTACHE_SSL=true
    -DCMAKE_C_COMPILER=$C_COMPILER_BIN
    -DCMAKE_CXX_COMPILER=$CPP_COMPILER_BIN

  # Release build
  - cmake -H.
    -BBuild-Release
    -DCMAKE_BUILD_TYPE=Release
    -DPISTACHE_SSL=true

script:
  - # Debug build
  - cd Build-Debug
  - make -j 2 all test ARGS="-V" VERBOSE=1

  - # Release build
  - cd ../Build-Release
  - make -j 2

after_failure:
  - ls -lta /var/crash
  - COREFILE=$(find ./ -maxdepth 1 -name "core*" -print | head -n 1) 
  - if [[ -f "$COREFILE" ]]; then
    gdb -c "$COREFILE" -ex "thread apply all bt" -ex "set pagination 0" -batch;
    fi

after_success:
- cd ../Build-Debug
- sudo su -c "echo 'if [ \"\$1\" = \"-v\" ] ; then $COV_TOOL --version ; else $COV_TOOL $COV_TOOL_ARGS \$@ ; fi' > /usr/local/bin/cov-tool" && sudo chmod +x /usr/local/bin/cov-tool
- lcov --capture --gcov-tool cov-tool --directory . --output-file coverage.info
- lcov --remove coverage.info '/usr/*' '*tests/*' '*googletest-release-1.7.0/*' --output-file coverage.info
- lcov --list coverage.info
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"