language: cpp
compiler:
  - clang
  - gcc

os:
  - linux

dists:
  - trusty
  - xenial

stages:
  - name: build
  - name: test
  - name: deploy

jobs:
  include:

    - stage: build
      script:
        - echo "build 01"
        - echo "build 02"

    - stage: build
      script:
        - echo "build 11"
        - echo "build 12"

    - stage: test
    - script: echo "test 1"
    - script: echo "test 2"

    - stage: deploy
    - script: echo "build 1"
    - script: echo "build 2"