language: cpp

stages:
  - "format"
  - "build"
  - "test"
  - "coverage"
  - "memcheck"
  - "build-release"

format: &format
  stage: format
  env:
    - CHECK=format
  script:
    - echo $CHECK

build: &build
  stage: build
  env:
    - CHECK=build
  script:
    - echo $CHECK

test: &test
  stage: test
  env:
    - CHECK=test
  script:
    - echo $CHECK

coverage: &coverage
  stage: coverage
  env:
    - CHECK=coverage
  script:
    - echo $CHECK

memcheck: &memcheck
  stage: memcheck
  env:
    - CHECK=memcheck
  script:
    - echo $CHECK

build-release: &build-release
  stage: build-release
  env:
    - CHECK=build-release
  script:
    - echo $CHECK

jobs:
  include:
    - <<:
      - *format
      - *build
      - *test
      - *coverage
      - *memcheck
      - *build-release