stages:
  - name: build
  - name: test
  # - name: deploy

jobs:
  include:
    -
      name: Build Job
      stage: build
      script:
        - echo "Builded" > build

    -
      name: Test Job
      stage: test
      script:
        - if [ "$(cat ./build)" = "Builded" ]; then echo "Success" && exit 0; else echo "Failed" && exit 1; fi